### ISSUE TITLE
Multiple tables in a query

### ISSUE THREAD

**Issue by shaneHowearth** [bokwoon95/go-structured-query#12]
Hi - I have a query that would be achieved in SQL like so
```
SELECT foo.A bar.B FROM A, B WHERE some predicate
```

I don't want to do a join (if I do it's a multi table join), and the second table's field is only used for an inner query

I cannot see a way to do that with this tool, have I missed something?

I've found that I can pass `nil` as a predicate - no idea what effect this will have on the query (yet, am testing)

**Comment by bokwoon95** [comment]
`CustomJoin` should cover that, you can supply a custom join string e.g.

```go
sq.Select(a.FOO).From(a).CustomJoin(",", b).Where(b.BAR.IsNull())
```
```sql
SELECT a.foo FROM a , b WHERE b.bar IS NOT NULL
```

works with any string really

```go
sq.Select(a.FOO).From(a).CustomJoin("LOREM IPSUM", b).Where(b.BAR.IsNull())
```
```sql
SELECT a.foo FROM a LOREM IPSUM b WHERE b.bar IS NOT NULL
```

> I've found that I can pass nil as a predicate

If I'm not wrong `nil` predicates would get printed as `NULL` into the query (not sure if that is correct or not). In the upcoming v2 I plan to change it so that it returns an error.
